name: PR Auto Assign and Label

on:
  pull_request:
    types: [ opened, reopened, edited ]

permissions:
  pull-requests: write
  issues: write

jobs:
  auto_assign_and_label:
    runs-on: ubuntu-latest

    steps:
      - name: Auto-assign PR
        uses: kentaro-m/auto-assign-action@v1.2.1
        with:
          configuration-path: '.github/auto_assign.yml'

      - name: Add labels based on PR title
        uses: actions/github-script@v7
        with:
          script: |
            const prTitle = context.payload.pull_request.title.toLowerCase();
            const labels = [];

            if (prTitle.startsWith('feat:')) {
              labels.push('feature');
            } else if (prTitle.startsWith('fix:')) {
              labels.push('bug');
            } else if (prTitle.startsWith('refactor:')) {
              labels.push('refactor');
            } else if (prTitle.startsWith('test:')) {
              labels.push('test');
            }

            if (labels.length > 0) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                labels: labels
              });
            }
