name: PR Auto Assign and Label

on:
  pull_request:
    types: [ opened, reopened, edited ]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  auto_assign_and_label:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-assign PR
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: '.github/auto_assign.yml'
          repo-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Add labels based on PR title
        if: github.event.pull_request && github.event.pull_request.title
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            
            if (!pr || !pr.title) {
            console.log("PR title is null, skipping labeling");
            } else {
            const prTitle = pr.title.toLowerCase();
            const labels = [];
            
            if (prTitle.startsWith('feat:')) labels.push('feature');
            else if (prTitle.startsWith('fix:')) labels.push('bug');
            else if (prTitle.startsWith('refactor:')) labels.push('refactor');
            else if (prTitle.startsWith('test:')) labels.push('test');
            
            if (labels.length > 0) {
            await github.rest.issues.addLabels({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: pr.number,
            labels: labels
            });
            }
            }